[[main]]
  name = "Chrome Web Store"
  parent = "install"
  url = "https://chrome.google.com/webstore/detail/page-notes/omjdheidbhoghpfdnndkgoelfiogjfla"
  weight = 10

[[main]]
  name = "Firefox"
  parent = "install"
  url = "https://addons.mozilla.org/en-US/firefox/addon/mg-page-notes/"
  weight = 20

[[main]]
  name = "Install"
  identifier = "install"
  weight = 10

[[main]]
  name = "Support"
  url = "https://github.com/manugarg/pagenotes-issues"
  weight = 20

[[social]]
  name = "Slack"
  pre = '<svg xmlns="http://www.w3.org/2000/svg" class="feather" width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"><path d="M22.08 9C19.81 1.41 16.54-.35 9 1.92S-.35 7.46 1.92 15 7.46 24.35 15 22.08 24.35 16.54 22.08 9z"></path><line x1="12.57" y1="5.99" x2="16.15" y2="16.39"></line><line x1="7.85" y1="7.61" x2="11.43" y2="18.01"></line><line x1="16.39" y1="7.85" x2="5.99" y2="11.43"></line><line x1="18.01" y1="12.57" x2="7.61" y2="16.15"></line></svg>'
  url = "https://join.slack.com/t/pagenotes/shared_invite/zt-1syzqesjb-24bCr8y5UyRrVBEiCpBLAQ"
  weight = 20

