# Meta Data for SEO

## Homepage
title = "Page Notes"
titleSeparator = "-"
titleAddition = "Take notes for web pages and access them with a single click whenever you visit those web pages again."
description = "Take notes for web pages and access them with a single click whenever you visit those web pages again. (Syncs to Google Drive)"
googleAnalytics = 'G-G7JEL0BW75'

## Open Graph
ogLocale = "en_US"
domainTLD = "manugarg.com"
titleHome = "Page Notes"

## Twitter Cards
twitterSite = "@cloudprober"
twitterCreator = "@manugarg"

## JSON-LD
schemaType = "Organization"
schemaName = "manugarg"
schemaAuthor = "Manu Garg"
schemaAuthorTwitter = "https://twitter.com/manugarg"
schemaAuthorLinkedIn = "https://www.linkedin.com/in/manugarg/"
schemaAuthorGitHub = "https://github.com/manugarg"
schemaLocale = "en-US"
schemaLogoWidth = 512
schemaLogoHeight = 512
schemaImageWidth = 1280
schemaImageHeight = 640
schemaLinkedIn = ""
schemaGitHub = "https://github.com/manugarg/pagenotes"
schemaSection = "blog"

## Sitelinks Search Box
siteLinksSearchBox = false

## Chrome Browser
themeColor = "#fff"

# Images - Temporarily left in place for backward compatibility
quality = 85
bgColor = "#fff"
landscapePhotoWidths = [900, 800, 700, 600, 500]
portraitPhotoWidths = [800, 700, 600, 500]
lqipWidth = "20x"
smallLimit = "300"

# Images
imageResponsive = true
imageConvertTo = "webp"
imageImageSizes = ["480","720","1080","1280","1600","2048"]
singleSize = false
imageAddClass = "img-fluid lazyload blur-up"

### Image template
defaultImage = "default-image.png" # put in `./assets/images/`
fillImage = "1270x740 Center" # normalize image size

# Footer
footer = "Website powered by <a class=\"text-muted\" href=\"https://gohugo.io/\">Hugo</a>, and <a class=\"text-muted\" href=\"https://getdoks.org/\">Doks</a>"

# Feed
copyRight = "Copyright (c) 2016-2023 Manu Garg"

# Alert
alert = false
alertDismissable = true

# Edit Page
repoHost = "GitHub"
docsRepo = "https://github.com/manugarg/pagenotes-issues"
docsRepoBranch = "master"
docsRepoSubPath = ""
editPage = false
lastMod = false

[options]
  lazySizes = true
  clipBoard = true
  instantPage = true
  flexSearch = true
  searchSectionsShow = []
  searchSectionsIndex = []
  darkMode = true
  bootStrapJs = true
  breadCrumb = false
  highLight = true
  kaTex = false
  multilingualMode = false
  docsVersioning = false
  fullWidth = false
  navbarSticky = true
  toTopButton = false
  scrollSpy = false # experimental; needs Bootstrap >= 5.2.0-beta1

[menu]
  [menu.section]
    auto = false
    collapsibleSidebar = false

